### ISSUE TITLE
Duplicate "_plugin" cause an ERROR

### ISSUE THREAD

**Issue by SnailRabbids** [funseek/godot-ios-att#1]
@yokochi Hi again :)
Warning appears when I'm using "Firebase Analytics" (https://github.com/funseek/godot-ios-firebase-analytics) plugin and "Att" plugin. 
Because of that "Att" plugin cannot be deinitialized. If I'm using one of this plugins w/o another, everything works fine. 

Error:
![image](https://user-images.githubusercontent.com/36141552/171154995-2d97e79b-d144-4d26-9425-000771894218.png)

Warning:
![image](https://user-images.githubusercontent.com/36141552/171155775-943fcf64-ee44-466f-a541-44949618c7f7.png)

Plugins works as expected, but fails when closing the app.
Steps for reproduce -> run via Xcode on IOS device -> see Warning -> application runs -> close application (double tap on main button -> swipe) -> see Error.
Error appears after "deinit Att plugin".

**Comment by yokochi** [comment]
@SnailRabbids Hi, Thanks for the report. I will check back later.

**Comment by yokochi** [comment]
@SnailRabbids I have fixed this problem. Please check the latest version. The following libraries also had the same problem and I have fixed it. Please bring them up to date if necessary.
https://github.com/funseek/godot-ios-firebase-analytics
https://github.com/funseek/godot-ios-firebase-message
https://github.com/funseek/godot-ios-request-review

**Comment by SnailRabbids** [comment]
@yokochi works for me. Thank you again :)
